### DEEP LEARNING 
- Pytorch Basic

In [1]:
import torch 
torch.cuda.is_available()

ModuleNotFoundError: No module named 'torch'

- Dataset with pytorch

In [61]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [62]:
df = pd.read_csv('./Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [63]:
df.shape

(150, 6)

In [64]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
X = df.drop(['Species'], axis=1).values
Y = le.fit_transform(df['Species'].values)

# Chia dữ liệu với text size = 20%
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
Y_train = torch.LongTensor(Y_train).reshape(-1, 1)
Y_test = torch.LongTensor(Y_test).reshape(-1, 1)

In [65]:
len(Y_train)

120

In [66]:
labels, counts = Y_train.unique(return_counts=True)
print(labels, counts)

tensor([0, 1, 2]) tensor([40, 41, 39])


#### **Tính đạo hàm bằng pytorch**
            y = 2x^4 + x^3 + 3x^2 + 5x + 1          
- *Tính y'*

In [67]:
import torch

In [68]:
x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)

tensor(2., requires_grad=True)
None


In [69]:
# Định nghĩa hàm
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [70]:
y.grad_fn

In [71]:
# Thực hiện lan truyền ngược và tính toán các gradient 
y.backward()

In [72]:
x.grad

tensor(93.)

---

##### **BTVN 1:**
            y = 5x^5 + 6x^3 + 3x + 1                

*Cho biết độ dốc của đa thức trên ở điểm nào?*

In [1]:
import torch

x = torch.tensor(1.0, requires_grad=True)
y = 5*x**5 + 6*x**3 + 3*x + 1
y.backward()

print("Giá trị x =", x.item())
print("Độ dốc tại điểm đó =", x.grad.item())


Giá trị x = 1.0
Độ dốc tại điểm đó = 46.0


---

##### **BTVN 2:** Tạo một tensor ban đầu có giá trị là 2. Định nghĩa hàm số và tính gradient
            y = x ^ 3 + 2x ^ 2 + 5x + 1             

- *Hãy tính dy/dx tại giá trị của x*

- *Dùng phương pháp Gradient Descent với Learning Rate Alpha = 0.1 để cập nhật giá trị x trong 10 vòng lặp*


In [2]:
import torch

x = torch.tensor(2.0, requires_grad=True)
y = x**3 + 2*x**2 + 5*x + 1
y.backward()

print("Giá trị x ban đầu =", x.item())
print("Gradient dy/dx tại x =", x.grad.item())

Giá trị x ban đầu = 2.0
Gradient dy/dx tại x = 25.0


In [4]:
alpha = 0.1
x = torch.tensor(2.0, requires_grad=True)

print("Tiến trình của Gradient Descent: ")
print("-" * 40)

for step in range(10):
    if x.grad is not None:
        x.grad.zero_()

    y = x**3 + 2*x**2 + 5*x + 1
    y.backward()
    with torch.no_grad():
        x -= alpha * x.grad
    
    print(f"Vòng {step+1:2d}: x = {x.item():.6f}, dy/dx = {x.grad.item():.6f}")

Tiến trình của Gradient Descent: 
----------------------------------------
Vòng  1: x = -0.500000, dy/dx = 25.000000
Vòng  2: x = -0.875000, dy/dx = 3.750000
Vòng  3: x = -1.254688, dy/dx = 3.796875
Vòng  4: x = -1.725085, dy/dx = 4.703972
Vòng  5: x = -2.427826, dy/dx = 7.027413
Vòng  6: x = -3.724998, dy/dx = 12.971715
Vòng  7: x = -6.897680, dy/dx = 31.726830
Vòng  8: x = -18.912006, dy/dx = 120.143257
Vòng  9: x = -119.146408, dy/dx = 1002.343933
Vòng 10: x = -4330.747559, dy/dx = 42116.011719


---

##### **BTVN 3:** Tạo một tập dữ liệu giả lập với x là số giờ học (ngẫu nhiên từ 1 - 10) và y là số điểm tính theo công thức: 
        
            y = 3x + 5 + noise             

**Ghi chú:** __*noise*__ là một giá trị ngẫu nhiên nhỏ

1. Khởi tạo tham số w và b ngẫu nhiên với requires_grad = True
2. Tính MSE
3. Tính Gradient
4. Cập nhật tham số w và b bằng Gradient Descent với learning rate alpha = 0.01
5. Lặp lại quá trình trên trong 100 vòng lặp để xem sự hội tụ của mô hình.

In [ ]:
import torch

torch.manual_seed(42)

x = torch.rand(50, 1) * 9 + 1 
noise = torch.randn(50, 1) * 0.5 
y = 3 * x + 5 + noise

In [6]:
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

In [7]:
def predict(x):
    return w * x + b

def mse_loss(y_pred, y_true):
    return torch.mean((y_pred - y_true) ** 2)

In [8]:
alpha = 0.01

In [9]:
print("Huấn luyện mô hình Linear Regression")
print("-" * 50)

for epoch in range(100):
    y_pred = predict(x)
    loss = mse_loss(y_pred, y)

    if w.grad is not None:
        w.grad.zero_()
    if b.grad is not None:
        b.grad.zero_()

    loss.backward()

    with torch.no_grad():
        w -= alpha * w.grad
        b -= alpha * b.grad

    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1:3d}: Loss = {loss.item():.4f}, w = {w.item():.4f}, b = {b.item():.4f}")

Huấn luyện mô hình Linear Regression
--------------------------------------------------
Epoch  10: Loss = 3.4119, w = 3.6961, b = 0.1707
Epoch  20: Loss = 3.2386, w = 3.6776, b = 0.3008
Epoch  30: Loss = 3.0747, w = 3.6597, b = 0.4272
Epoch  40: Loss = 2.9198, w = 3.6422, b = 0.5502
Epoch  50: Loss = 2.7732, w = 3.6253, b = 0.6698
Epoch  60: Loss = 2.6346, w = 3.6087, b = 0.7862
Epoch  70: Loss = 2.5035, w = 3.5927, b = 0.8993
Epoch  80: Loss = 2.3795, w = 3.5771, b = 1.0093
Epoch  90: Loss = 2.2622, w = 3.5619, b = 1.1163
Epoch 100: Loss = 2.1513, w = 3.5471, b = 1.2203


---

In [1]:
# Pytorch with Tensor
import torch 
import numpy as np

In [74]:
torch.__version__

'2.7.1+cpu'

In [75]:
# Chuyển đổi mảng numpy sang tensor pytorch
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int32
<class 'numpy.ndarray'>


In [76]:
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


In [77]:
print(x.dtype)

torch.int32


In [78]:
print(x.type())

torch.IntTensor


In [79]:
arr2 = np.arange(0.,12.).reshape(4,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [80]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [81]:
# Copy and sharing
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


In [82]:
arr[0] = 99
print(x)

tensor([99,  2,  3,  4,  5], dtype=torch.int32)


In [83]:
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [84]:
arr[0] = 99
print(x)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


---

##### **BTVN 4:** Giải thích 2 trường hợp ở trên:

--> Đó là do:

**1.** Sự khác nhau trong kết quả xuất phát từ cách tạo tensor trong PyTorch.

**2.** Khi tensor được tạo bằng `torch.from_numpy()`, PyTorch chia sẻ cùng vùng nhớ với mảng NumPy.Vì vậy, khi giá trị của mảng NumPy thay đổi thì giá trị của tensor cũng thay đổi theo

**3.** Ngược lại, khi tensor được tạo bằng `torch.tensor()`, PyTorch tạo một bản sao dữ liệu mới và không dùng chung bộ nhớ với mảng NumPy.Do đó, việc thay đổi mảng NumPy sẽ không ảnh hưởng đến tensor đã được tạo

---

##### **BTVN 5:** 
- Bạn giúp thầy tạo tensor với:

**1. Tạo tensor rỗng (empty)**
```python
    import torch

    t_empty = torch.empty(2, 3)
    print(t_empty)

**2. Tạo tensor toàn số 0 (zeros)**
```python
    import torch
    
    t_zeros = torch.zeros(2, 3)
    print(t_zeros)

**3. Tạo tensor toàn số 1 (ones)**
```python
    import torch
    
    t_ones = torch.ones(2, 3)
    print(t_ones)

**4. Tạo tensor ngẫu nhiên (random)**
```python
    import torch
    
    t_random = torch.rand(2, 3)
    print(t_random)

**5. Thay đổi hình dạng tensor (reshape)**
```python
# Dùng view()
    import torch

    x = torch.arange(1, 7)
    x_view = x.view(2, 3)
    print(x_view)
    
# Dùng view as()
    import torch

    y = torch.zeros(2, 3)
    x_view_as = x.view_as(y)
    print(x_view_as)