# DEEP LEARNING 

## TUẦN 2: NUMPY, PANDAS, MATPLOTLIB

# NUMBY

In [1]:
# NUMBY là thư viện kiểu list
# vì :
#+ numby nhanh 
#+ có nhiều hàm tích hợp dễ sử dụng cho AI 

# để sử dụng numpy thì : pip install numpy
import numpy as np

In [2]:
# thử tạo 1 list 
python_list = [1, 2, 3]
numpy_list = np.array(python_list)

type(numpy_list)  # sẽ trả về numpy.ndarray

numpy.ndarray

In [3]:
# list trong python có thể hỗ trợ nhiều loại trong list

my_list = [1, "chào",True , 2.0]

In [6]:
my_list = [1, 2, 3, 4.5]
np_list = np.array(my_list)
np_list 

array([1. , 2. , 3. , 4.5])

In [7]:
# Chuyển đổi dữ liệu thi sao ?

np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4])

In [11]:
# accesing và indexing 
x = np.array([1, 2, 3, 4, 5, 6, 7, 8]) # x = np.array(range(1,9))

In [12]:
# lấy số 4 
x[3]

np.int64(4)

In [13]:
# lấy nhiều hơn 1 phần tử 
# công thức [start:end:step]
#lấy 1 2 3 
x[0:3]

array([1, 2, 3])

In [15]:
# lấy từ 3 - 8 theo 3 cách
x[2:8]
x[2:]
x[2:8:1]

array([3, 4, 5, 6, 7, 8])

In [16]:
# không đúng 
x[2:-1]

array([3, 4, 5, 6, 7])

In [18]:
# lấy số 3 số 5
x[2],x[4]

(np.int64(3), np.int64(5))

In [19]:
# đặt danh sách các index muốn truy cập
x[[2, 4]]

array([3, 5])

In [20]:
data = [[1, 2], [3, 4], [5, 6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# lấy số 2
np_list[0,1]

array([[1, 2]])

In [ ]:
# lấy 3 4 5 6 
np_list[1:, :]


array([[3, 4],
       [5, 6]])

In [30]:
# cách 2
np_list[[1,2], :]

array([[3, 4],
       [5, 6]])

In [29]:
# cách 3 
np_list[1:]

array([[3, 4],
       [5, 6]])

In [31]:
# cách 4 
np_list[-2:]

array([[3, 4],
       [5, 6]])

In [41]:
# lấy 1, 3, 5 
np_list[:, 0]


array([1, 3, 5])

In [ ]:
# lấy 1 và 5 theo 2 cách
np_list[[0,2], 0]



array([1, 5])

In [47]:
np_list[[-1,0], 0]

array([5, 1])

In [48]:
np_list[0::2,0]

array([1, 5])

In [49]:
x = ([
  [1, 2, 3, 4],
  [5, 6, 7, 8],
  [9, 10, 11, 12],
  [13, 14, 15, 16]])

np_list = np.array(x)
np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [50]:
# lấy 2 6 10 14 
np_list[:,1]

array([ 2,  6, 10, 14])

In [51]:
#lấy 7 và 11
np_list[1:3,2]

array([ 7, 11])

In [ ]:
#lấy 7 và 11
np_list[[1,2],2]

In [ ]:
# lấy 4 7 10


array([[13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8]])

In [66]:
# lấy 16 15 14 13
np_list[3::3]



array([[13, 14, 15, 16]])

# BTVN 1
## Cho ma trận = [[99,99,99],
##                [99,99,99],
##                [99,99,99]]

### hãy tưởng tượng ô 99 trống 
### giả sử 1 là x 
### giả sử 0 là o

### lấy đầu vào từ phía X và phía O luân phiên 
### nếu đầu vào từ phía x là (0,0)

### ma trận sẽ trở thành 
## [[x,99,99],
##  [99,99,99],
##  [99,99,99]]

# nếu đầu vào từ phía O cũng là (0,0)
# thông báo nhập lại 
# nếu không điền vào ma trận 

# thử thách: Nếu người đầu tiên có 3 phần tử liên tiếp thì dừng trò chơi.



In [ ]:
board = [[99, 99, 99], [99, 99, 99], [99, 99, 99]]
player = 'X'

def show():
    for row in board:
        print([cell if cell == 99 else ('X' if cell == 1 else 'O') for cell in row])

def check_win():
    for i in range(3):
        if board[i][0] == board[i][1] == board[i][2] != 99: return True
        if board[0][i] == board[1][i] == board[2][i] != 99: return True
    if board[0][0] == board[1][1] == board[2][2] != 99: return True
    if board[0][2] == board[1][1] == board[2][0] != 99: return True
    return False

while True:
    show()
    try:
        r, c = map(int, input(f"{player} nhập (dòng,cột): ").split(','))
        if board[r][c] != 99:
            print("Ô đã có, nhập lại!")
            continue
        board[r][c] = 1 if player == 'X' else 0
        
        if check_win():
            show()
            print(f"{player} thắng!")
            break
            
        player = 'O' if player == 'X' else 'X'
    except:
        print("Nhập sai, ví dụ: 0,1")

[99, 99, 99]
[99, 99, 99]
[99, 99, 99]
Nhập sai, ví dụ: 0,1
[99, 99, 99]
[99, 99, 99]
[99, 99, 99]
Nhập sai, ví dụ: 0,1
[99, 99, 99]
[99, 99, 99]
[99, 99, 99]
Nhập sai, ví dụ: 0,1
[99, 99, 99]
[99, 99, 99]
[99, 99, 99]
[99, 'X', 99]
[99, 99, 99]
[99, 99, 99]
Ô đã có, nhập lại!
[99, 'X', 99]
[99, 99, 99]
[99, 99, 99]
[99, 'X', 'O']
[99, 99, 99]
[99, 99, 99]
Nhập sai, ví dụ: 0,1
[99, 'X', 'O']
[99, 99, 99]
[99, 99, 99]
['X', 'X', 'O']
[99, 99, 99]
[99, 99, 99]
Nhập sai, ví dụ: 0,1
['X', 'X', 'O']
[99, 99, 99]
[99, 99, 99]
Nhập sai, ví dụ: 0,1
['X', 'X', 'O']
[99, 99, 99]
[99, 99, 99]
Nhập sai, ví dụ: 0,1
['X', 'X', 'O']
[99, 99, 99]
[99, 99, 99]


In [1]:
# BTVN 2
y = (
    [1,2,3],
    [4,5,6],
    [7,8,9]
)

# Lấy 4,5,6

# Lấy 2,5 
# Lấy 3,4
# Lấy 9,6,3

In [2]:
# Lấy 4,5,6
print(y[1]) 

[4, 5, 6]


In [3]:
# Lấy 2,5 
print([y[0][1], y[1][1]])

[2, 5]


In [4]:
# Lấy 3,4
print([y[0][2], y[1][0]])

[3, 4]


In [5]:
# Lấy 9,6,3
print([y[2][2], y[1][2], y[0][2]])

[9, 6, 3]


In [11]:
# BTVN 3 

# Cho x = [1,2,3,4,5,6,7,8,9,10]
x = [1,2,3,4,5,6,7,8,9,10]
# 1. Xuất ra các giá trị chẵn sử dụng if

for i in x:
    if i % 2 == 0:
        print(i)


2
4
6
8
10


In [12]:

# 2. Xuất ra các giá trị chẵn sử dụng list comprehension
even_numbers = [i for i in x if i % 2 == 0]
print(even_numbers)

[2, 4, 6, 8, 10]


In [67]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np_x[np_x % 2 == 0]

array([0, 2, 4, 6, 8])

In [69]:
np_x % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [70]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
idx = [True , True, True, False, True, True, True, False, True, False]
np_x[idx]

array([0, 1, 2, 4, 5, 6, 8])

In [72]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
cond1 = np_x % 2 != 0
cond2 = np_x < 5
cond3 = np_x > 0

np_x[cond1 & cond2 | cond3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# BTVN 4
# Tạo 1 mảng numpy có kích thước 150 x 5 . Giả sử mảng này chứa 150 mảng dữ liệu 
# của nhân viên bao gồm chiều cao , cân nặng , tuổi , lương và điểm trung bình
# Tách mảng dựa trên 4 cột đầu tiên thành 1 biến có tên là x và cột cuối cùng thành y

# Tách mảng x thành x_train và x_test với trong đó x_train chứa 70% dữ liệu và tách y thành y_train và y_test chứa 70% dữ liệu

# Tạo 10 tập dữ liệu x_train không chồng chéo nhau
  

In [15]:
import numpy as np

# Tạo mảng 150 x 5
np.random.seed(42)  # Để kết quả có thể tái tạo
data = np.random.randn(150, 5)
print(f"Kích thước mảng: {data.shape}")
print("5 dòng đầu tiên của mảng:")
print(data[:5])
print("-" * 50)

Kích thước mảng: (150, 5)
5 dòng đầu tiên của mảng:
[[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
 [-0.23413696  1.57921282  0.76743473 -0.46947439  0.54256004]
 [-0.46341769 -0.46572975  0.24196227 -1.91328024 -1.72491783]
 [-0.56228753 -1.01283112  0.31424733 -0.90802408 -1.4123037 ]
 [ 1.46564877 -0.2257763   0.0675282  -1.42474819 -0.54438272]]
--------------------------------------------------


In [17]:
# Tách thành x (4 cột đầu) và y (cột cuối)
x = data[:, :4]
y = data[:, 4]
print(f"Kích thước x: {x.shape}")
print(f"Kích thước y: {y.shape}")
print("x (5 dòng đầu):")
print(x[:5])
print("y (5 giá trị đầu):")
print(y[:5])
print("-" * 50)

Kích thước x: (150, 4)
Kích thước y: (150,)
x (5 dòng đầu):
[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23413696  1.57921282  0.76743473 -0.46947439]
 [-0.46341769 -0.46572975  0.24196227 -1.91328024]
 [-0.56228753 -1.01283112  0.31424733 -0.90802408]
 [ 1.46564877 -0.2257763   0.0675282  -1.42474819]]
y (5 giá trị đầu):
[-0.23415337  0.54256004 -1.72491783 -1.4123037  -0.54438272]
--------------------------------------------------


In [18]:
# Tách mảng dựa trên 4 cột đầu tiên thành 1 biến có tên là x và cột cuối cùng thành y
n_samples = len(x)
n_train = int(0.7 * n_samples)
x_train = x[:n_train]
x_test = x[n_train:]
y_train = y[:n_train]
y_test = y[n_train:]

print(f"Số mẫu train: {n_train}, số mẫu test: {n_samples - n_train}")
print(f"x_train shape: {x_train.shape}")
print(f"x_test shape: {x_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")
print("-" * 50)

Số mẫu train: 105, số mẫu test: 45
x_train shape: (105, 4)
x_test shape: (45, 4)
y_train shape: (105,)
y_test shape: (45,)
--------------------------------------------------


In [20]:
#Tạo 10 tập dữ liệu x_train không chồng chéo nhau
n_folds = 10
fold_size = n_train // n_folds
print(f"Kích thước mỗi fold: {fold_size} mẫu")

x_folds = []
for i in range(n_folds):
    start_idx = i * fold_size
    end_idx = start_idx + fold_size
    x_fold = x_train[start_idx:end_idx]
    x_folds.append(x_fold)
    print(f"Fold {i+1}: chỉ số {start_idx}-{end_idx-1}, shape: {x_fold.shape}")

print("\nKiểm tra không chồng chéo:")
total_samples = sum([fold.shape[0] for fold in x_folds])
print(f"Tổng số mẫu trong 10 folds: {total_samples}")
print(f"Số mẫu x_train: {x_train.shape[0]}")
print(f"Kiểm tra: {total_samples} == {x_train.shape[0]}? {total_samples == x_train.shape[0]}")

Kích thước mỗi fold: 10 mẫu
Fold 1: chỉ số 0-9, shape: (10, 4)
Fold 2: chỉ số 10-19, shape: (10, 4)
Fold 3: chỉ số 20-29, shape: (10, 4)
Fold 4: chỉ số 30-39, shape: (10, 4)
Fold 5: chỉ số 40-49, shape: (10, 4)
Fold 6: chỉ số 50-59, shape: (10, 4)
Fold 7: chỉ số 60-69, shape: (10, 4)
Fold 8: chỉ số 70-79, shape: (10, 4)
Fold 9: chỉ số 80-89, shape: (10, 4)
Fold 10: chỉ số 90-99, shape: (10, 4)

Kiểm tra không chồng chéo:
Tổng số mẫu trong 10 folds: 100
Số mẫu x_train: 105
Kiểm tra: 100 == 105? False
